# Generated by pkg-ext
from tfdo._internal.inspect.cmd_inspect import inspect_hcl_paths_cmd as _inspect_hcl_paths_cmd
from tfdo._internal.inspect.cmd_inspect import inspect_resource_usage_cmd as _inspect_resource_usage_cmd

inspect_hcl_paths_cmd = _inspect_hcl_paths_cmd
inspect_resource_usage_cmd = _inspect_resource_usage_cmd
