# Generated by pkg-ext
from tfdo._internal.new.cmd_new import backend_cmd as _backend_cmd
from tfdo._internal.new.cmd_new import run_dir_cmd as _run_dir_cmd

backend_cmd = _backend_cmd
run_dir_cmd = _run_dir_cmd
