# Generated by pkg-ext
from tfdo._internal.schema.cmd_schema import schema_diff_cmd as _schema_diff_cmd
from tfdo._internal.schema.cmd_schema import schema_show_cmd as _schema_show_cmd
from tfdo._internal.schema.diff import ResourceSchemaChange as _ResourceSchemaChange
from tfdo._internal.schema.diff import SchemaDiffResult as _SchemaDiffResult

schema_diff_cmd = _schema_diff_cmd
schema_show_cmd = _schema_show_cmd
ResourceSchemaChange = _ResourceSchemaChange
SchemaDiffResult = _SchemaDiffResult
