# Generated by pkg-ext
from tfdo._internal.sync.cmd_sync import github_cmd as _github_cmd
from tfdo._internal.sync.cmd_sync import justfile_cmd as _justfile_cmd

github_cmd = _github_cmd
justfile_cmd = _justfile_cmd
